Create User
wolox-training/fc-graphql pull request #6
Opened 2019-07-10 22:41 UTC by FrancoCoronel

## Summary
- Modify mutation to create an user

## Trello card
https://trello.com/c/RZnfgzMd/23-sign-up

2019-07-11 16:00 UTC, gonziesc requested changes

2019-07-11 16:00 UTC, gonziesc commented on package.json
> +    "bcrypt": "^3.0.6",
use bcrypt js

2019-07-12 20:54 UTC, igna92ts requested changes

2019-07-12 20:54 UTC, igna92ts commented on app/services/users.js
> +  user.password = await bcrypt.hash(password, constants.SALT_ROUNDS);
shouldnt this also be inside the try?

2019-08-06 14:12 UTC, gonziesc approved these changes

2019-08-06 14:21 UTC, merged